### ISSUE TITLE
License incompatibility

### ISSUE THREAD

**Issue by LeoColomb** [jaytaph/Transphpile#9]
Hi!

Your work in this repository seems very interesting and may receive more focus, contribution and improvement.
That said, I'm facing an issue with your license, since [all rights are reserved to you](https://github.com/jaytaph/Transphpile/blob/d9b379713fcb026fabd4845266c27788a05f1324/LICENSE#L2) (then no right for derivative and contribution).

This is quite ambigus with open source! :smile_cat: 

> Copyright (c) 2016, Joshua Thijssen
> **All rights reserved.**

**Comment by TimothyBJacobs** [comment]
This is a standard [BSD-3](https://opensource.org/licenses/BSD-3-Clause) license. I think you are confusing copyright and licensing.

**Comment by LeoColomb** [comment]
@TimothyBJacobs OMG, you're right. Thanks!
